// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(2))
	{
	case 0:
		character\mp_british_commando01::main();
		break;
	case 1:
		character\mp_british_airborne01::main();
		break;
	}
}

precache()
{
	character\mp_british_commando01::precache();
	character\mp_british_airborne01::precache();
}
