// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(1))
	{
	case 0:
		character\mp_british_commando01_winter::main();
		break;
	}
}

precache()
{
	character\mp_british_commando01_winter::precache();
}
